### PR TITLE
Remove links 5

### PR DESCRIPTION
**Pull request by Planeshifter**
We are excited about your pull request, but unfortunately we are not accepting pull requests against this repository, as all development happens on the [main project repository](https://github.com/stdlib-js/stdlib). We kindly request that you submit this pull request against the [respective directory](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/property-symbols) of the main repository where we’ll review and provide feedback. 

If this is your first stdlib contribution, be sure to read the [contributing guide](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md) which provides guidelines and instructions for submitting contributions. You may also consult the [development guide](https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md) for help on developing stdlib.

We look forward to receiving your contribution! :smiley:

### CODE REVIEW

**Comment by Planeshifter** [comment]
@kgryte Looking good now?

**Comment by kgryte** [comment]
@Planeshifter Yes, looks great!

**Comment by Planeshifter** [comment]
@kgryte Thinking about it, we should also link to the respective directory of the main project in the bot comment:

> We kindly request that you submit this pull request against the [respective directory](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/property-symbols) of the main repository where we’ll review and provide feedback.

**Comment by kgryte** [comment]
Sounds good to me.

**Pull request closed without merging**
